<h3>Slider Widget</h3>
<?php
	$quantitySlider = $block->getData('quantity_slider');
	if ( count($quantitySlider) > 0) {
?>
<div class="block-slider autoplay">
 	<?php
		for ($i = 0; $i < $quantitySlider; $i++) {
 	?>
  		<div class="image">
 			<img src="http://magentotest.com/pub/media/catalog/product/l/t/lt01.jpg" alt="">
		</div>
	<?php
		}
 	?>
</div>
<?php
	}
?>
<script type="text/x-magento-init">
    {
        ".block-slider": {
            "slick.lib": {
            	"slidesToShow": 3,
                "dots": true
            }
        }
    }
</script>
